apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    application: kube-aws-autoscaler
    version: v0.10
  name: kube-aws-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-aws-autoscaler
  template:
    metadata:
      labels:
        application: kube-aws-autoscaler
        version: v0.10
      annotations:
        # FIXME: using hardcoded IAM role
        iam.amazonaws.com/role: kube-1-app-autoscaler
    spec:
      containers:
      - name: autoscaler
        image: hjacobs/kube-aws-autoscaler:0.10
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
